POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Created from MongoDB 😊",
    "important": true,
    "userId": "60627711f7050c26b0e56b2f"
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json
